services:
    - type: web
      name: telegram-symfony-bot
      env: docker
      plan: free
      autoDeploy: true
      envVars:
          - key: APP_ENV
            value: prod
          - key: DATABASE_URL
            fromDatabase:
                name: telegram_pg
                property: connectionString
          - key: TELEGRAM_BOT_TOKEN
            sync: false # установи вручную через UI Render

databases:
    - name: telegram_pg
      plan: free
      postgresMajorVersion: 15
